name: Documentation

on:
  push:
    branches: [ main ]

jobs:
  dokka:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate docs
        run: |
          ./gradlew dokkaHtml
          mv ./app/build/dokka/html ./docs
      - name: Deploy docs
        uses: actions-go/push@v1
        with:
          force: true
          remote: origin
          remote-ref: gh-pages
          commit-message: '[Auto] update docs'
