name: Documentation

on:
  push:
    branches: [ main ]

jobs:
  dokka:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate docs
        run: |
          ./gradlew dokkaHtml
          mv ./app/build/dokka/html ./docs
      - name: Commit changes
        run: |
          git config --local user.email "github-actions@noreply.github.com"
          git config --local user.name "Github Actions"
          git add -f docs
          git diff-index --quiet HEAD || git commit -m "Auto extract docs"
      - name: Deploy docs
        run: |
          git fetch origin gh-pages
          git push -u origin gh-pages --force
